<?php

return [
    'definitions' => [
        'profile' => [
            'label' => 'Profil Saya',
            'description' => 'Akses halaman profil pengguna sendiri',
            'group' => 'account',
        ],
        'users' => [
            'label' => 'Pengguna',
            'description' => 'Kelola data master pengguna',
            'group' => 'master',
        ],
        'users.manage' => [
            'label' => 'Kelola Data Pengguna',
            'description' => 'Tambah, edit, dan hapus akun pengguna',
            'group' => 'master',
        ],
        'employees' => [
            'label' => 'Karyawan',
            'description' => 'Kelola data karyawan',
            'group' => 'master',
        ],
        'employees.destroy' => [
            'label' => 'Hapus Karyawan',
            'description' => 'Hapus data karyawan',
            'group' => 'master',
        ],
        'employee_levels' => [
            'label' => 'Level Karyawan',
            'description' => 'Kelola master level karyawan',
            'group' => 'master',
        ],
        'work_schedules' => [
            'label' => 'Jadwal Kerja',
            'description' => 'Kelola master jam kerja dan shift karyawan',
            'group' => 'master',
        ],
        'departments' => [
            'label' => 'Departemen',
            'description' => 'Kelola data departemen',
            'group' => 'master',
        ],
        'positions' => [
            'label' => 'Posisi',
            'description' => 'Kelola data posisi',
            'group' => 'master',
        ],
        'work_locations' => [
            'label' => 'Lokasi Kerja',
            'description' => 'Kelola data lokasi kerja',
            'group' => 'master',
        ],
        'tenants' => [
            'label' => 'Tenant',
            'description' => 'Kelola data tenant',
            'group' => 'master',
        ],
        'roles' => [
            'label' => 'Role',
            'description' => 'Kelola data role dan hak akses',
            'group' => 'master',
        ],
        'attendances' => [
            'label' => 'Absensi',
            'description' => 'Kelola data absensi',
            'group' => 'operational',
        ],
        'attendances.manage' => [
            'label' => 'Kelola Data Absensi',
            'description' => 'Tambah, edit, dan hapus data absensi',
            'group' => 'operational',
        ],
        'attendances.destroy' => [
            'label' => 'Hapus Data Absensi',
            'description' => 'Hapus data absensi',
            'group' => 'operational',
        ],
        'leaves' => [
            'label' => 'Cuti / Izin',
            'description' => 'Kelola data cuti dan izin',
            'group' => 'operational',
        ],
        'leaves.create' => [
            'label' => 'Ajukan / Buat Cuti',
            'description' => 'Buat atau ajukan permintaan cuti',
            'group' => 'operational',
        ],
        'leaves.manage' => [
            'label' => 'Kelola Data Cuti',
            'description' => 'Edit, setujui, ekspor, dan hapus data cuti',
            'group' => 'operational',
        ],
        'leaves.destroy' => [
            'label' => 'Hapus Data Cuti',
            'description' => 'Hapus permintaan cuti',
            'group' => 'operational',
        ],
        'leaves.analytics' => [
            'label' => 'Analitik Cuti',
            'description' => 'Lihat dashboard analitik cuti',
            'group' => 'operational',
        ],
        'leaves.reports' => [
            'label' => 'Laporan Cuti / Izin',
            'description' => 'Lihat laporan cuti dan izin',
            'group' => 'operational',
        ],
        'leaves.approval.supervisor' => [
            'label' => 'Persetujuan Cuti Supervisor',
            'description' => 'Menyetujui tahap awal permintaan cuti multi approval sebagai supervisor',
            'group' => 'operational',
        ],
        'leaves.approval.manager' => [
            'label' => 'Persetujuan Cuti Manager',
            'description' => 'Menyetujui tahap manager untuk permintaan cuti',
            'group' => 'operational',
        ],
        'leaves.approval.hr' => [
            'label' => 'Persetujuan Cuti HR',
            'description' => 'Menyetujui tahap akhir permintaan cuti sebagai HR',
            'group' => 'operational',
        ],
        'payroll' => [
            'label' => 'Gaji / Payroll',
            'description' => 'Kelola proses payroll',
            'group' => 'operational',
        ],
        'payroll.reports' => [
            'label' => 'Laporan Payroll',
            'description' => 'Lihat laporan payroll',
            'group' => 'operational',
        ],
        'lembur' => [
            'label' => 'Lembur',
            'description' => 'Akses modul lembur',
            'group' => 'operational',
        ],
        'lembur.submit' => [
            'label' => 'Pengajuan Lembur',
            'description' => 'Ajukan lembur baru',
            'group' => 'operational',
        ],
        'lembur.approval' => [
            'label' => 'Persetujuan Lembur',
            'description' => 'Tinjau dan setujui pengajuan lembur',
            'group' => 'operational',
        ],
        'lembur.reports' => [
            'label' => 'Laporan Lembur',
            'description' => 'Lihat ringkasan dan laporan lembur',
            'group' => 'operational',
        ],
        'payroll.manage' => [
            'label' => 'Kelola Payroll',
            'description' => 'Proses dan administrasi payroll',
            'group' => 'operational',
        ],
        'reports' => [
            'label' => 'Laporan',
            'description' => 'Lihat laporan HRIS',
            'group' => 'operational',
        ],
    ],
    'defaults' => [
        'admin_hr' => [
            'profile',
            'users',
            'users.manage',
            'employees',
            'employees.destroy',
            'employee_levels',
            'departments',
            'positions',
            'work_locations',
            'tenants',
            'roles',
            'attendances',
            'attendances.manage',
            'attendances.destroy',
            'leaves',
            'leaves.create',
            'leaves.manage',
            'leaves.destroy',
            'leaves.analytics',
            'leaves.reports',
            'leaves.approval.hr',
            'lembur',
            'lembur.submit',
            'lembur.approval',
            'lembur.reports',
            'payroll',
            'payroll.manage',
            'payroll.reports',
            'reports',
        ],
        'manager' => [
            'profile',
            'users',
            'employees',
            'employee_levels',
            'work_locations',
            'attendances',
            'attendances.manage',
            'leaves',
            'leaves.manage',
            'leaves.analytics',
            'leaves.reports',
            'leaves.approval.manager',
            'lembur',
            'lembur.submit',
            'lembur.approval',
        ],
        'supervisor' => [
            'profile',
            'employees',
            'attendances',
            'leaves',
            'leaves.approval.supervisor',
        ],
        'employee' => [
            'profile',
            'attendances',
            'leaves',
            'leaves.create',
            'lembur',
            'lembur.submit',
        ],
    ],
];
